import { ethers } from 'ethers';
import * as dotenv from 'dotenv';

dotenv.config();

// Import contract ABIs (generated by Hardhat)
import InvoiceNFTArtifact from '../../artifacts/contracts/InvoiceNFT.sol/InvoiceNFT.json';
import LoanEscrowArtifact from '../../artifacts/contracts/LoanEscrow.sol/LoanEscrow.json';

export class BaseService {
  private provider: ethers.Provider;
  private wallet: ethers.Wallet;

  constructor() {
    // Validate required environment variables
    const required = ['BASE_RPC_URL', 'PRIVATE_KEY', 'INVOICE_NFT_ADDRESS', 'LOAN_ESCROW_ADDRESS'];
    const missing = required.filter(key => !process.env[key]);

    if (missing.length > 0) {
      throw new Error(
        `Missing required environment variables for BaseService: ${missing.join(', ')}\n` +
        `Please ensure your .env file is configured correctly. See .env.example for reference.`
      );
    }

    this.provider = new ethers.JsonRpcProvider(process.env.BASE_RPC_URL);
    this.wallet = new ethers.Wallet(process.env.PRIVATE_KEY!, this.provider);
  }

  getInvoiceNFTContract() {
    return new ethers.Contract(
      process.env.INVOICE_NFT_ADDRESS!,
      InvoiceNFTArtifact.abi,
      this.wallet
    );
  }

  getLoanEscrowContract() {
    return new ethers.Contract(
      process.env.LOAN_ESCROW_ADDRESS!,
      LoanEscrowArtifact.abi,
      this.wallet
    );
  }

  async mintInvoiceNFT(
    ownerAddress: string,
    debtorAddress: string,
    amountEth: number,
    daysUntilDue: number
  ): Promise<{ tokenId: number; txHash: string }> {
    const contract = this.getInvoiceNFTContract();
    const amount = ethers.parseEther(amountEth.toString());
    const dueDate = Math.floor(Date.now() / 1000) + daysUntilDue * 86400;

    const tx = await contract.mint(ownerAddress, debtorAddress, amount, dueDate);
    const receipt = await tx.wait();

    // Parse event to get token ID
    const invoiceMintedEvent = contract.interface.getEvent('InvoiceMinted');
    if (!invoiceMintedEvent) {
      throw new Error('InvoiceMinted event not found in contract interface');
    }
    const event = receipt.logs.find(
      (log: any) => log.topics && log.topics[0] === invoiceMintedEvent.topicHash
    );
    if (!event || !event.topics) {
      throw new Error('InvoiceMinted event not found in transaction receipt');
    }
    const tokenId = parseInt(event.topics[1], 16);

    return { tokenId, txHash: receipt.hash };
  }

  async getInvoiceDetails(tokenId: number) {
    const contract = this.getInvoiceNFTContract();
    const invoice = await contract.getInvoice(tokenId);

    return {
      debtor: invoice.debtor,
      amount: ethers.formatEther(invoice.amount),
      dueDate: new Date(Number(invoice.dueDate) * 1000).toISOString(),
      paid: invoice.paid,
    };
  }

  async createLoan(
    borrowerAddress: string,
    invoiceTokenId: number,
    principalEth: number,
    interestEth: number
  ): Promise<{ loanId: number; txHash: string }> {
    const escrowContract = this.getLoanEscrowContract();
    const invoiceNFT = this.getInvoiceNFTContract();
    const escrowAddress = await escrowContract.getAddress();
    const invoiceNFTAddress = process.env.INVOICE_NFT_ADDRESS!;
    const principal = ethers.parseEther(principalEth.toString());
    const interest = ethers.parseEther(interestEth.toString());

    // CRITICAL: Approve escrow to transfer NFT before creating loan
    console.log(`[Base] Approving escrow ${escrowAddress} to transfer NFT ${invoiceTokenId}`);
    const approvalTx = await invoiceNFT.approve(escrowAddress, invoiceTokenId);
    await approvalTx.wait();
    console.log(`[Base] NFT approved for escrow transfer`);

    const tx = await escrowContract.createLoan(
      borrowerAddress,
      invoiceNFTAddress,
      invoiceTokenId,
      principal,
      interest,
      { value: principal }
    );

    const receipt = await tx.wait();

    // Parse event to get loan ID
    const loanCreatedEvent = contract.interface.getEvent('LoanCreated');
    if (!loanCreatedEvent) {
      throw new Error('LoanCreated event not found in contract interface');
    }
    const event = receipt.logs.find(
      (log: any) => log.topics && log.topics[0] === loanCreatedEvent.topicHash
    );
    if (!event || !event.topics) {
      throw new Error('LoanCreated event not found in transaction receipt');
    }
    const loanId = parseInt(event.topics[1], 16);

    return { loanId, txHash: receipt.hash };
  }

  async settleLoan(loanId: number, paymentEth: number): Promise<string> {
    const contract = this.getLoanEscrowContract();
    const payment = ethers.parseEther(paymentEth.toString());

    const tx = await contract.settleLoan(loanId, { value: payment });
    const receipt = await tx.wait();

    return receipt.hash;
  }
}

export const baseService = new BaseService();
